[package]
name = "capnp-rust-proj"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp = "0.18.11"

[build-dependencies]
capnpc = "0.18.0"
